---
- name: Install Docker
  hosts: all

  tasks:

  - name: Update apt packages
    apt:
      update_cache: "yes"
      force_apt_get: "yes"
    become: yes

  - name: Install packages needed for Docker
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: present
      force_apt_get: "yes"
    become: yes

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: yes

  - name: Save the current Ubuntu release version into a variable
    shell: lsb_release -cs
    register: ubuntu_version

  - name: Add Docker Repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
      state: present
    become: yes

  - name: Update apt packages
    apt:
      update_cache: "yes"
      force_apt_get: "yes"
    become: yes

  - name: Install Docker
    apt:
      name: "docker-ce"
      state: present
      force_apt_get: "yes"
    become: yes