---
- name: Install Docker
  hosts: remote

  tasks:

  # - name: Update apt packages
  #   shell: apt-get update
  #   become: yes

  # - name: Install packages needed for Docker
  #   shell:
  #     apt-get install \
  #     apt-transport-https \
  #     ca-certificates \
  #     curl \
  #     gnupg \
  #     lsb-release
  #   become: yes

  # - name: Add Docker GPG apt Key
  #   shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  #   become: yes

  - name: Add Docker GPG apt Key
    shell:
      echo \
      \"deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable\" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    become: yes

  - name: Update apt packages
    shell: apt-get update
    become: yes

  - name: Install Docker
    shell: apt-get install docker-ce docker-ce-cli containerd.io
    become: yes
